Experimental: baking channel to vertex color can support Alpha channel
ucupumar/ucupaint pull request #79
Opened 2024-01-03 12:49 UTC by morirain

2024-01-03 12:54 UTC, morirain commented
Test: 4.0, 2.93
I did a little work on your code :), It basically creates a temp vertex color, then bakes it twice, and merges the results.

2024-01-03 12:56 UTC, morirain commented
Reference #78

2024-01-03 13:01 UTC, ucupumar commented
Thanks for the pull request. Ok, I'll test it first 👍

2024-01-03 14:02 UTC, ucupumar commented on bake_common.py
> +            origin_vcol_name = get_active_vertex_color(obj).name
I think you should pass bake vcol name to bake_to_vcol function and try to get the vcol based on that name. I think it's safer that way.

2024-01-05 07:05 UTC, ucupumar commented
@morirain I just reviewed your code. Can you make a tweak with your code?

2024-01-05 07:08 UTC, morirain commented
> @morirain I just reviewed this pull request. Can you make a tweak to your code?

@ucupumar Okay. Any suggestions :)?

2024-01-05 07:14 UTC, ucupumar requested changes

2024-01-05 07:14 UTC, ucupumar commented
I thought I already pressed the review button. There we go 😁

2024-01-05 07:18 UTC, morirain commented
OK, I'll start later, and then I'll test it with a model with a lot of vertices👌

2024-01-05 12:17 UTC, morirain commented
The updated code has been uploaded, then i tested two models, one with 2 million vertices in 30 seconds and one with 500,000 vertices in 7 seconds.

2024-01-05 19:25 UTC, ucupumar commented
Ok, good enough, I'll merge this pull request, thanks for your contribution! 🙏

2024-01-05 19:25 UTC, merged